apiVersion: cmpp.io/v1alpha1
kind: CMPPProxy
metadata:
  name: example-cmppproxy
spec:
  image: sinoreps/cmppproxy:latest
  account: "333"
  password: "0555"
  numConnections: 1
  serverAddr: "127.0.0.1"
  serviceCode: "9999"
  enterpriseCode: "044022"